version: '2'
services:
    calimetro-app:
        image: calimetro
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://calimetro-mysql:3306/calimetro?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    calimetro-mysql:
        extends:
            file: mysql.yml
            service: calimetro-mysql
